blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/Polar-Team/Polar-Gosling-Compute-Module/discussions
    about: Ask questions or discuss ideas with the community
